### ISSUE TITLE
Overlay

### ISSUE THREAD

**Issue by montogeek** [eyaleizenberg/react-native-custom-action-sheet#5]
Hi!

It looks like the overlay that this component implements does not hide when the `visibleModal` is set to `false`.

Here is my setup:

``` js
<CustomActionSheet modalVisible={this.state.modalVisible} onCancel={this.toggleModal}>
     <View style={{backgroundColor: 'white', marginBottom: 10, borderRadius: 5}}>
          <DatePickerIOS mode={"date"} date={this.state.date} onDateChange={this.onDateChange} />
      </View>
</CustomActionSheet>
```

`modalVisible` is set to `false` by default, the component is hidden but I can't click anywhere in the page, when I Inspect the page it shows that is an `ActionModal`.

**Comment by montogeek** [comment]
I just found out that it needs to be wrapped by a `View`. That should be documented. Can I? Thanks :)

**Comment by alenliang** [comment]
i run into that issue too, agree this should be documented.

**Comment by eyaleizenberg** [comment]
Hi @montogeek , how about you open a pull request?

**Comment by montogeek** [comment]
Well, is already documented :)
https://github.com/eyaleizenberg/react-native-custom-action-sheet/commit/c9b66fbd3084e31ce89d4b0c38c6ac8c319b24f5#diff-04c6e90faac2675aa89e2176d2eec7d8R21
