### ISSUE TITLE
Cancel Button

### ISSUE THREAD

**Issue by iyawnis** [eyaleizenberg/react-native-custom-action-sheet#7]
It would make sense to be able to pass the text for the Cancel button. Also, renaming the default button to 'close' seems reasonable

**Comment by eyaleizenberg** [comment]
@latusaki  Sounds good, do you want to create a pull request?

**Comment by iyawnis** [comment]
ah.. just took a look at the code, this is done here.. https://github.com/eyaleizenberg/react-native-custom-action-sheet/commit/b52a74f217dfdada2baf3ba42690e3dbe01aa142
